apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.fullname" . }}-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jellyfin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "jellyfin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: jellyfin-streaming
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
            - name: media
              mountPath: /media
              readOnly: true
            {{- if .Values.persistence.fonts.enabled }}
            - name: fonts
              mountPath: /usr/local/share/fonts/custom
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-pvc-config
        - name: cache
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.fullname" . }}-pvc-cache
        - name: media
          hostPath:
            path: {{ .Values.persistence.media }}
        {{- if .Values.persistence.fonts.enabled }}
        - name: fonts
          hostPath:
            path: {{ .Values.persistence.fonts.path }}
        {{- end }}
