{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jellyfin.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-secure-headers@kubernetescrd
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "jellyfin.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
