apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.config }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.persistence.cache }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
---
