{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-runner
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
{{- end }}
