apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare.name" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
data:
  config.yaml: |
    tunnel: {{ .Values.tunnelId }}
    credentials-file: {{ .Values.paths.credentials }}

    ingress:
      - hostname: {{ .Values.hostname }}
        service: https://traefik.{{ .Values.traefikNamespace }}.svc.cluster.local:443
        originRequest:
          originServerName: {{ .Values.hostname }}   # SNI → matches origin cert CN/SAN
          httpHostHeader: {{ .Values.hostname }}     # keep Host header consistent
          # noTLSVerify: true                        # uncomment only for test/debug
      - service: http_status:404

    metrics: 0.0.0.0:2000
    no-autoupdate: true
