apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare.name" . }}-deploy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudflare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflare.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cloudflare.name" . }}-sa
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - tunnel
            - --no-autoupdate
            - --config={{ .Values.paths.config }}
            - run
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 2000
          env:
            - name: TUNNEL_CRED_FILE
              value: {{ .Values.paths.credentials }}
          volumeMounts:
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cfg
              mountPath: /etc/cloudflared/config
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: cloudflared-credentials
            items:
              - key: credentials.json
                path: credentials.json
        - name: cfg
          configMap:
            name: {{ include "cloudflare.name" . }}-config
            items:
              - key: config.yaml
                path: config.yaml
