apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "traefik-sec.fullname" . }}-headers
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "traefik-sec.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: {{ .Values.headers.hstsSeconds }}
    stsIncludeSubdomains: {{ .Values.headers.includeSubdomains }}
    stsPreload: {{ .Values.headers.preload }}
    referrerPolicy: {{ .Values.headers.referrerPolicy | quote }}
    frameDeny: {{ .Values.headers.frameDeny }}
    browserXssFilter: true
    contentTypeNosniff: true
    contentSecurityPolicy: {{ .Values.headers.contentSecurityPolicy | quote }}
